apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
  namespace: argo-events
  annotations:
    configsync.gke.io/cluster-name-selector: np-mgmt-cluster-azure
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: release-dependency
      eventSourceName: github-webhook
      eventName: demo
      filters:
        data:
          # Type of Github event that triggered the delivery: [pull_request, push, issues, label, ...]
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: headers.X-Github-Event
            type: string
            value:
              - release
          - path: body.action
            type: string
            value:
              - created
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: buildkit-
              spec:
                entrypoint: docker-build-push
                arguments:
                  parameters:
                    - name: release-tag
                    - name: git-repository-url
                volumeClaimTemplates:
                  - metadata:
                      name: workdir
                    spec:
                      accessModes: [ "ReadWriteOnce" ]
                      resources:
                        requests:
                          storage: 1Gi
                serviceAccountName: argo-events-sa
                templates:
                  - name: docker-build-push
                    inputs:
                      parameters:
                        - name: release-tag
                        - name: git-repository-url
                    steps:
                      - - name: git-clone
                          template: git-clone
                          arguments:
                            parameters:
                              - name: git-repository-url
                                value: "{{inputs.parameters.git-repository-url}}"
                      - - name: kaniko-build
                          template: kaniko-build
                          arguments:
                            parameters:
                              - name: release-tag
                                value: "{{inputs.parameters.release-tag}}"
                  - name: git-clone
                    inputs:
                      parameters:
                        - name: git-repository-url
                    container:
                      image: alpine/git
                      command: [git, clone, "{{inputs.parameters.git-repository-url}}", "/workdir/repo"]
                      volumeMounts:
                      - name: workdir
                        mountPath: /workdir
                  - name: kaniko-build
                    inputs:
                      parameters:
                        - name: release-tag
                    metadata:
                      labels:
                        azure.workload.identity/use: "true" # This is required by Azure to use Workload Identity
                    container:
                      image: gcr.io/kaniko-project/executor:debug
                      command: ["/kaniko/executor"]
                      args: [
                        "--dockerfile=/workdir/repo/app/Dockerfile",
                        "--context=/workdir/repo/app",
                        "--destination=nonproductionacr.azurecr.io/my-python-flask-app:{{inputs.parameters.release-tag}}"
                      ]
                      volumeMounts:
                      - name: workdir
                        mountPath: /workdir
                  - name: ls-repo
                    container:
                      image: alpine:latest
                      command: [sh, -c]
                      args: ["ls /workdir/repo/app"]
                      volumeMounts:
                      - name: workdir
                        mountPath: /workdir
          parameters:
            - src:
                dependencyName: release-dependency
                dataKey: body.release.tag_name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: release-dependency
                dataKey: body.repository.html_url
              dest: spec.arguments.parameters.1.value
      retryStrategy:
        steps: 3