apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-webhook-secret
  namespace: argo-events
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: github-webhook-secret
    creationPolicy: Owner
  data:
  - secretKey: github-webhook-secret
    remoteRef:
      key: github-webhook-secret